
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/Investments?createDatabaseIfNotExist = true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database: default
    hibernate:
      ddl-auto: create

    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  
