#server:
#port: 9191

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/Investment?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database: default
    hibernate:
      ddl-auto: update

    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  
