
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/Investment   #?createDatabaseIfNotExist
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org,hibernate.boot.model.PhysicalNamingStrategyStandardImpl

  
